#!/usr/bin/env bash

IMAGE_NAME="giogt/wildfly"
IMAGE_VERSION_MAJOR="11.0"
IMAGE_VERSION_MINOR=".0.Final"

docker build -t ${IMAGE_NAME}:${IMAGE_VERSION_MAJOR}${IMAGE_VERSION_MINOR} . && \
docker tag ${IMAGE_NAME}:${IMAGE_VERSION_MAJOR}${IMAGE_VERSION_MINOR} ${IMAGE_NAME}:${IMAGE_VERSION_MAJOR}
